### ISSUE TITLE
[错误/BUG]克隆后使用npm安装依赖问题

### ISSUE THREAD

**Issue by iPlanC** [mcthesw/game-save-manager#11]
**问题简述 Describe the bug**
package.json 中未安装 archiver 依赖包、依赖存在冲突或缺失。

**如何触发错误 To Reproduce**
```shell
npm install
npm run electron:build
npm install archiver --save
npm run electron:build
```

**正确表现 Expected behavior**
克隆后`npm install`，再使用`npm run electron:build`生成打包文件

**截图 Screenshots**
```shell
PS D:\Projects\game-save-manager> npm install

> game-save-manager@0.3.0 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.14.5

added 1847 packages in 4m
```
```shell
PS D:\Projects\game-save-manager> npm run electron:build

> game-save-manager@0.3.0 electron:build
> vue-cli-service electron:build

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Bundling render process:

✔  Building modern bundle for production...
 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
```
```shell
PS D:\Projects\game-save-manager> vue-cli-service electron:build
 ERROR  TypeError: transpileDependencies.map is not a function
TypeError: transpileDependencies.map is not a function
    at genTranspileDepRegex (D:\Projects\game-save-manager\node_modules\@vue\cli-plugin-babel\index.js:6:38)
    at module.exports (D:\Projects\game-save-manager\node_modules\@vue\cli-plugin-babel\index.js:22:29)
    at C:\Users\planc\AppData\Roaming\npm\node_modules\@vue\cli-service\lib\Service.js:82:9
    at Array.forEach (<anonymous>)
    at loadedCallback (C:\Users\planc\AppData\Roaming\npm\node_modules\@vue\cli-service\lib\Service.js:80:20)
    at Service.init (C:\Users\planc\AppData\Roaming\npm\node_modules\@vue\cli-service\lib\Service.js:97:14)
    at Service.run (C:\Users\planc\AppData\Roaming\npm\node_modules\@vue\cli-service\lib\Service.js:247:16)
    at Object.<anonymous> (C:\Users\planc\AppData\Roaming\npm\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
```

**环境 Desktop:**
 - 操作系统 [Windows 10 21H2 19044.2006]
 - 软件版本 [0.3.0]
 - Nodejs版本  [16.17.1]
 - npm版本 [8.19.2]
 - npm源 [淘宝镜像源]

**其余信息 Additional context**
似乎是由archiver依赖导致的问题

**Comment by mcthesw** [comment]
我会在近期进行检查，感谢你的反馈

**Comment by iPlanC** [comment]
```
PS C:\Users\planc> npm list -g
+-- @vue/cli-service@5.0.8
+-- archiver@5.3.1
+-- cnpm@8.3.0
+-- electron-builder@23.3.3
+-- npm@8.19.2
+-- vue-cli@2.9.6
+-- vue@3.2.39
+-- webpack-cli@4.10.0
`-- webpack@5.74.0
```

**Comment by mcthesw** [comment]
在[该次commit](https://github.com/mcthesw/game-save-manager/commit/d93ca4190df7086a805f453ae6beb06a167a5eda)后已经加入了archiver，感谢反馈，经过测试，已经可以正常运行了，你那里成功运行了吗

**Comment by iPlanC** [comment]
依然是不能打包，这个程序需要用到全局包吗，用到了哪些呢？

**Comment by iPlanC** [comment]
```
PS D:\Projects\game-save-manager> npm list -g
C:\Users\planc\AppData\Roaming\npm
├── @vue/cli-service@5.0.8
├── @vue/cli@5.0.8
├── electron@21.0.0
├── npm@8.19.2
├── vue@3.2.39
└── webpack@5.74.0
```
这套配置经测试可以打包生成
